### ISSUE TITLE
Selinux, rebooting everytime regardless of setting

### ISSUE THREAD

**Issue by dvalinrh** [redhat-performance/zathras#70]

**Comment by jharriga** [comment]
I am seeing this behavior as well.
I manually configured the SUT with selinux 'disabled'.
Then added this line to zathras scenario file:
selinux_state: disabled

I see this in stdout for the run ( $ ./burden –scenario scenario.mariadb  )
TASK [selinux_config : disabling selinux for RHEL/Amazon] **********************
changed: [10.26.9.89]

TASK [selinux_config : reboot the system now for disabled selinux to take effect] ***

Perhaps the playbook could use the result from 'getenforce' to determine if an selinux
cfg change is actually required and avoid these unnecessary reboots.

**Comment by dvalinrh** [comment]
Fixed.
