### ISSUE TITLE
install script needs work

### ISSUE THREAD

**Issue by dvalinrh** [redhat-performance/zathras#83]
install script needs to
 1) Install specific versions of software
 2) Bail on errors

What i had to do earlier (edited) 
pip install 'ansible==v2.9.6'
pip install 'yq==2.10.0'
pip install jinja2==3.0.3
That was just version pieces after I ran your install script.
I had to do numerous other package installs  also.  Best way to get it all, is to install a machine clean with rhel 9, and then try things (I was on a lab machine)

**Comment by grdumas** [comment]
I completed testing using a clean RHEL 9 (virtual) machine. After changing the package name 'ansible' to 'ansible-core' and fixing yq to version 2.10.0 I was able to successfully install Zathras and use this installation to execute tests on another system.

I am continuing to work adding proper error handling to the installation script.
